# .github/workflows/pages.yml
name: Pages

on:
  push:
    branches:
      - master # default branch 修改为使用的分支名

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 将源码clone到运行环境中
      - uses: actions/checkout@v4.0.0
        with:
            submodules: 'true' # 这里因为使用了子模块，设置为true
      # 配置Node.js环境
      - name: Use Node.js 16.x
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "16" # 这里需要修改为对应的Node.js版本
      - name: Cache NPM dependencies
        uses: actions/cache@v4.0.0
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      # 安装依赖环境
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
